services:
  mariadb:
    image: mariadb:11
    container_name: inventario-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: inventario
      MARIADB_CHARACTER_SET_SERVER: utf8mb4
      MARIADB_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
